
def stringclean(string):
    print(string)
    # string = string.encode('utf-8')
    # print(string)
    string = str(string)
    # _, string = string.split('b', 1)

    string = string.replace(r'\xe2\x82\xac', '€')
    string = string.replace(r'\\xe2\\x82\\xac', '€')
    print(string)
    string = string.replace(r'\xc2\xa0', '')
    string = string.replace(r'\\xc2\\xa0', '')
    print(string)
    string = string.replace(r'\xe2\x80\x93', '-')
    string = string.replace(r'\\xe2\\x80\\x93', '-')
    print(string)
    string = string.replace(r'\xe2\x80\x94', '-')
    string = string.replace(r'\\xe2\\x80\\x94', '-')
    print(string)
    string = string.replace(r'\xe2\x80\x98', "'")
    string = string.replace(r'\\xe2\\x80\\x98', "'")
    print(string)
    string = string.replace(r"\xe2\x80\x99", "'")
    string = string.replace(r"\\xe2\\x80\\x99", "'")
    print(string)
    string = string.replace(r'\xe2\x80\x9c', '"')
    string = string.replace(r'\\xe2\\x80\\x9c', '"')
    print(string)
    string = string.replace(r'\xe2\x80\x9d', '"')
    string = string.replace(r'\\xe2\\x80\\x9d', '"')
    print(string)
    string = string.replace(r'\\xe2\\x80\\xa6', '...')
    string = string.replace(r'\xe2\x80\xa6', '...')
    print(string)
    string = string.replace(r'\xe3\x80\x8e', '')
    string = string.replace(r'\\xe3\\x80\\x8e', '')
    print(string)
    string = string.replace(r'\\xe3\\x80\\x8f', '')
    string = string.replace(r'\xe3\x80\x8f', '')
    print(string)
    string = string.replace(r'\xc2\xa3', '€')
    string = string.replace(r'\\xc2\\xa3', '€')
    print(string)
    string = string.replace(r"\xc3\xbc", 'ü')
    string = string.replace(r"\\xc3\\xbc", 'ü')
    string = string.replace(r"\\'", "'")
    print(string)
    string = string.replace(r"\'", "'")
    print(string)
    string = string.lstrip('"')
    print(string)
    string = string.rstrip('"')
    print(string)
    string = string.lstrip("'")
    print(string)
    string = string.rstrip("'")
    print(string)
    string = string.lstrip('"')
    print(string)
    string = string.rstrip('"')
    print(string)

    return string

